### ISSUE TITLE
[Request] Figma version of this icon pack

### ISSUE THREAD

**Issue by kandevis** [omar-hanafy/enefty_icons#4]
Hello author,

I would like to ask you a figma version of this icon pack. For UI/UX team in my project to able to use it in app graphic design.
Thank you very much.

**Comment by omar-hanafy** [comment]
Hi @honghai2196 

The Figma link got deleted by the author, but I have all the icons in SVG format. You can find them here:

enefty_icons/lib/assets/

There are two zip files:

	1.	all-iconset.zip - All SVGs.
	2.	flutter-supported-iconset.zip - SVGs supported in the Flutter package.

Hope this helps!
